//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/dimitarbogdanov/Documents/Projects/hayc/HaycLib/Hay.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


// CLI compliance attribute
#pragma warning disable CS3021
namespace HaycLib.Antlr;

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public partial class HayParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		BLOCK_COMMENT=1, LINE_COMMENT=2, WS=3, IMPORT=4, FUNCTION=5, NAMESPACE=6, 
		STRUCT=7, INITIALIZER=8, RETURN=9, STRING=10, DEC_INT=11, HEX_INT=12, 
		DEC_DOUBLE=13, AMPERSAND=14, ASSIGN=15, LPAREN=16, RPAREN=17, LBRACE=18, 
		RBRACE=19, DOUBLE_COLON=20, SEMICOLON=21, COLON=22, DOT=23, COMMA=24, 
		AT=25, IDENTIFIER=26;
	public const int
		RULE_file = 0, RULE_namespaceImport = 1, RULE_namespaceDeclaration = 2, 
		RULE_topLevelConstruct = 3, RULE_structDeclaration = 4, RULE_structBody = 5, 
		RULE_structInitializer = 6, RULE_structField = 7, RULE_functionDeclaration = 8, 
		RULE_statementBlock = 9, RULE_statement = 10, RULE_variableDeclaration = 11, 
		RULE_parameterList = 12, RULE_parameter = 13, RULE_expressionList = 14, 
		RULE_expression = 15, RULE_typeName = 16, RULE_name = 17, RULE_number = 18, 
		RULE_string = 19;
	public static readonly string[] ruleNames = {
		"file", "namespaceImport", "namespaceDeclaration", "topLevelConstruct", 
		"structDeclaration", "structBody", "structInitializer", "structField", 
		"functionDeclaration", "statementBlock", "statement", "variableDeclaration", 
		"parameterList", "parameter", "expressionList", "expression", "typeName", 
		"name", "number", "string"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, "'import'", "'function'", "'namespace'", "'struct'", 
		"'initializer'", "'return'", null, null, null, null, "'&'", "'='", "'('", 
		"')'", "'{'", "'}'", "'::'", "';'", "':'", "'.'", "','", "'@'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "BLOCK_COMMENT", "LINE_COMMENT", "WS", "IMPORT", "FUNCTION", "NAMESPACE", 
		"STRUCT", "INITIALIZER", "RETURN", "STRING", "DEC_INT", "HEX_INT", "DEC_DOUBLE", 
		"AMPERSAND", "ASSIGN", "LPAREN", "RPAREN", "LBRACE", "RBRACE", "DOUBLE_COLON", 
		"SEMICOLON", "COLON", "DOT", "COMMA", "AT", "IDENTIFIER"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Hay.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static HayParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public HayParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public HayParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NamespaceDeclarationContext namespaceDeclaration() {
			return GetRuleContext<NamespaceDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(HayParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NamespaceImportContext[] namespaceImport() {
			return GetRuleContexts<NamespaceImportContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NamespaceImportContext namespaceImport(int i) {
			return GetRuleContext<NamespaceImportContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TopLevelConstructContext[] topLevelConstruct() {
			return GetRuleContexts<TopLevelConstructContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TopLevelConstructContext topLevelConstruct(int i) {
			return GetRuleContext<TopLevelConstructContext>(i);
		}
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 0, RULE_file);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 43;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IMPORT) {
				{
				{
				State = 40;
				namespaceImport();
				}
				}
				State = 45;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 46;
			namespaceDeclaration();
			State = 50;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==FUNCTION || _la==STRUCT) {
				{
				{
				State = 47;
				topLevelConstruct();
				}
				}
				State = 52;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 53;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceImportContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IMPORT() { return GetToken(HayParser.IMPORT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		public NamespaceImportContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespaceImport; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespaceImport(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceImportContext namespaceImport() {
		NamespaceImportContext _localctx = new NamespaceImportContext(Context, State);
		EnterRule(_localctx, 2, RULE_namespaceImport);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 55;
			Match(IMPORT);
			State = 56;
			name(0);
			State = 57;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NAMESPACE() { return GetToken(HayParser.NAMESPACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		public NamespaceDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespaceDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespaceDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceDeclarationContext namespaceDeclaration() {
		NamespaceDeclarationContext _localctx = new NamespaceDeclarationContext(Context, State);
		EnterRule(_localctx, 4, RULE_namespaceDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			Match(NAMESPACE);
			State = 60;
			name(0);
			State = 61;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TopLevelConstructContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StructDeclarationContext structDeclaration() {
			return GetRuleContext<StructDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public FunctionDeclarationContext functionDeclaration() {
			return GetRuleContext<FunctionDeclarationContext>(0);
		}
		public TopLevelConstructContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_topLevelConstruct; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTopLevelConstruct(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TopLevelConstructContext topLevelConstruct() {
		TopLevelConstructContext _localctx = new TopLevelConstructContext(Context, State);
		EnterRule(_localctx, 6, RULE_topLevelConstruct);
		try {
			State = 65;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case STRUCT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 63;
				structDeclaration();
				}
				break;
			case FUNCTION:
				EnterOuterAlt(_localctx, 2);
				{
				State = 64;
				functionDeclaration();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructDeclarationContext : ParserRuleContext {
		public IToken structName;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRUCT() { return GetToken(HayParser.STRUCT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StructBodyContext structBody() {
			return GetRuleContext<StructBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(HayParser.IDENTIFIER, 0); }
		public StructDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructDeclarationContext structDeclaration() {
		StructDeclarationContext _localctx = new StructDeclarationContext(Context, State);
		EnterRule(_localctx, 8, RULE_structDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 67;
			Match(STRUCT);
			State = 68;
			_localctx.structName = Match(IDENTIFIER);
			State = 69;
			structBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructBodyContext : ParserRuleContext {
		public StructFieldContext fields;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(HayParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(HayParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StructInitializerContext[] structInitializer() {
			return GetRuleContexts<StructInitializerContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructInitializerContext structInitializer(int i) {
			return GetRuleContext<StructInitializerContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructFieldContext[] structField() {
			return GetRuleContexts<StructFieldContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructFieldContext structField(int i) {
			return GetRuleContext<StructFieldContext>(i);
		}
		public StructBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructBodyContext structBody() {
		StructBodyContext _localctx = new StructBodyContext(Context, State);
		EnterRule(_localctx, 10, RULE_structBody);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			Match(LBRACE);
			State = 75;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==INITIALIZER) {
				{
				{
				State = 72;
				structInitializer();
				}
				}
				State = 77;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==IDENTIFIER) {
				{
				{
				State = 78;
				_localctx.fields = structField();
				}
				}
				State = 83;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 84;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructInitializerContext : ParserRuleContext {
		public ParameterListContext parameters;
		public StatementBlockContext body;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INITIALIZER() { return GetToken(HayParser.INITIALIZER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(HayParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(HayParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParameterListContext parameterList() {
			return GetRuleContext<ParameterListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementBlockContext statementBlock() {
			return GetRuleContext<StatementBlockContext>(0);
		}
		public StructInitializerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structInitializer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructInitializer(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructInitializerContext structInitializer() {
		StructInitializerContext _localctx = new StructInitializerContext(Context, State);
		EnterRule(_localctx, 12, RULE_structInitializer);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(INITIALIZER);
			State = 87;
			Match(LPAREN);
			State = 88;
			_localctx.parameters = parameterList();
			State = 89;
			Match(RPAREN);
			State = 90;
			_localctx.body = statementBlock();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructFieldContext : ParserRuleContext {
		public IToken fieldName;
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(HayParser.IDENTIFIER, 0); }
		public StructFieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structField; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructField(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructFieldContext structField() {
		StructFieldContext _localctx = new StructFieldContext(Context, State);
		EnterRule(_localctx, 14, RULE_structField);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			typeName();
			State = 93;
			_localctx.fieldName = Match(IDENTIFIER);
			State = 94;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDeclarationContext : ParserRuleContext {
		public NameContext ownerStruct;
		public IToken functionName;
		public ParameterListContext parameters;
		public TypeNameContext returnType;
		public StatementBlockContext body;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FUNCTION() { return GetToken(HayParser.FUNCTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(HayParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(HayParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(HayParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(HayParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParameterListContext parameterList() {
			return GetRuleContext<ParameterListContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementBlockContext statementBlock() {
			return GetRuleContext<StatementBlockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(HayParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		public FunctionDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDeclarationContext functionDeclaration() {
		FunctionDeclarationContext _localctx = new FunctionDeclarationContext(Context, State);
		EnterRule(_localctx, 16, RULE_functionDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96;
			Match(FUNCTION);
			State = 99;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==AT) {
				{
				State = 97;
				Match(AT);
				State = 98;
				_localctx.ownerStruct = name(0);
				}
			}

			State = 101;
			_localctx.functionName = Match(IDENTIFIER);
			State = 102;
			Match(LPAREN);
			State = 103;
			_localctx.parameters = parameterList();
			State = 104;
			Match(RPAREN);
			State = 105;
			Match(COLON);
			State = 106;
			_localctx.returnType = typeName();
			State = 107;
			_localctx.body = statementBlock();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementBlockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(HayParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(HayParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public StatementBlockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statementBlock; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatementBlock(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementBlockContext statementBlock() {
		StatementBlockContext _localctx = new StatementBlockContext(Context, State);
		EnterRule(_localctx, 18, RULE_statementBlock);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109;
			Match(LBRACE);
			State = 113;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RETURN) | (1L << STRING) | (1L << DEC_INT) | (1L << HEX_INT) | (1L << DEC_DOUBLE) | (1L << SEMICOLON) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 110;
				statement();
				}
				}
				State = 115;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 116;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
	 
		public StatementContext() { }
		public virtual void CopyFrom(StatementContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ExpressionStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		public ExpressionStatementContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class EmptyStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		public EmptyStatementContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEmptyStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ReturnStatementContext : StatementContext {
		public ExpressionContext value;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(HayParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ReturnStatementContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturnStatement(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VariableDeclarationStatementContext : StatementContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		public VariableDeclarationStatementContext(StatementContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclarationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 20, RULE_statement);
		int _la;
		try {
			State = 130;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				_localctx = new EmptyStatementContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 118;
				Match(SEMICOLON);
				}
				break;
			case 2:
				_localctx = new VariableDeclarationStatementContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 119;
				variableDeclaration();
				State = 120;
				Match(SEMICOLON);
				}
				break;
			case 3:
				_localctx = new ReturnStatementContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 122;
				Match(RETURN);
				State = 124;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << DEC_INT) | (1L << HEX_INT) | (1L << DEC_DOUBLE) | (1L << IDENTIFIER))) != 0)) {
					{
					State = 123;
					((ReturnStatementContext)_localctx).value = expression(0);
					}
				}

				State = 126;
				Match(SEMICOLON);
				}
				break;
			case 4:
				_localctx = new ExpressionStatementContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 127;
				expression(0);
				State = 128;
				Match(SEMICOLON);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationContext : ParserRuleContext {
		public IToken variableName;
		public ExpressionContext value;
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(HayParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(HayParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public VariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationContext variableDeclaration() {
		VariableDeclarationContext _localctx = new VariableDeclarationContext(Context, State);
		EnterRule(_localctx, 22, RULE_variableDeclaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			typeName();
			State = 133;
			_localctx.variableName = Match(IDENTIFIER);
			{
			State = 134;
			Match(ASSIGN);
			State = 135;
			_localctx.value = expression(0);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ParameterContext[] parameter() {
			return GetRuleContexts<ParameterContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParameterContext parameter(int i) {
			return GetRuleContext<ParameterContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(HayParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(HayParser.COMMA, i);
		}
		public ParameterListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameterList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParameterListContext parameterList() {
		ParameterListContext _localctx = new ParameterListContext(Context, State);
		EnterRule(_localctx, 24, RULE_parameterList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IDENTIFIER) {
				{
				State = 137;
				parameter();
				State = 142;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 138;
					Match(COMMA);
					State = 139;
					parameter();
					}
					}
					State = 144;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterContext : ParserRuleContext {
		public IToken paramName;
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(HayParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(HayParser.IDENTIFIER, 0); }
		public ParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParameterContext parameter() {
		ParameterContext _localctx = new ParameterContext(Context, State);
		EnterRule(_localctx, 26, RULE_parameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			typeName();
			State = 148;
			_localctx.paramName = Match(IDENTIFIER);
			State = 149;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionListContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(HayParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(HayParser.COMMA, i);
		}
		public ExpressionListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionList; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionListContext expressionList() {
		ExpressionListContext _localctx = new ExpressionListContext(Context, State);
		EnterRule(_localctx, 28, RULE_expressionList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			expression(0);
			State = 156;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 152;
				Match(COMMA);
				State = 153;
				expression(0);
				}
				}
				State = 158;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
	 
		public ExpressionContext() { }
		public virtual void CopyFrom(ExpressionContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class NameReferenceExpressionContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		public NameReferenceExpressionContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNameReferenceExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class StringExpressionContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public StringContext @string() {
			return GetRuleContext<StringContext>(0);
		}
		public StringExpressionContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class NumberExpressionContext : ExpressionContext {
		[System.Diagnostics.DebuggerNonUserCode] public NumberContext number() {
			return GetRuleContext<NumberContext>(0);
		}
		public NumberExpressionContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class AccessExpressionContext : ExpressionContext {
		public ExpressionContext target;
		public IToken child;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(HayParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(HayParser.IDENTIFIER, 0); }
		public AccessExpressionContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAccessExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class VariableAssignmentExpressionContext : ExpressionContext {
		public ExpressionContext target;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(HayParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public VariableAssignmentExpressionContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableAssignmentExpression(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class FunctionCallExpressionContext : ExpressionContext {
		public ExpressionContext target;
		public ExpressionListContext arguments;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(HayParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(HayParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionListContext expressionList() {
			return GetRuleContext<ExpressionListContext>(0);
		}
		public FunctionCallExpressionContext(ExpressionContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionCallExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 30;
		EnterRecursionRule(_localctx, 30, RULE_expression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 163;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DEC_INT:
			case HEX_INT:
			case DEC_DOUBLE:
				{
				_localctx = new NumberExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 160;
				number();
				}
				break;
			case STRING:
				{
				_localctx = new StringExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 161;
				@string();
				}
				break;
			case IDENTIFIER:
				{
				_localctx = new NameReferenceExpressionContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 162;
				name(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 179;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 177;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
					case 1:
						{
						_localctx = new VariableAssignmentExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((VariableAssignmentExpressionContext)_localctx).target = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 165;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 166;
						Match(ASSIGN);
						State = 167;
						expression(2);
						}
						break;
					case 2:
						{
						_localctx = new AccessExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((AccessExpressionContext)_localctx).target = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 168;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 169;
						Match(DOT);
						State = 170;
						((AccessExpressionContext)_localctx).child = Match(IDENTIFIER);
						}
						break;
					case 3:
						{
						_localctx = new FunctionCallExpressionContext(new ExpressionContext(_parentctx, _parentState));
						((FunctionCallExpressionContext)_localctx).target = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 171;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 172;
						Match(LPAREN);
						State = 174;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
						if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << STRING) | (1L << DEC_INT) | (1L << HEX_INT) | (1L << DEC_DOUBLE) | (1L << IDENTIFIER))) != 0)) {
							{
							State = 173;
							((FunctionCallExpressionContext)_localctx).arguments = expressionList();
							}
						}

						State = 176;
						Match(RPAREN);
						}
						break;
					}
					} 
				}
				State = 181;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,15,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TypeNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name() {
			return GetRuleContext<NameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AMPERSAND() { return GetToken(HayParser.AMPERSAND, 0); }
		public TypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeNameContext typeName() {
		TypeNameContext _localctx = new TypeNameContext(Context, State);
		EnterRule(_localctx, 32, RULE_typeName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			name(0);
			State = 184;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==AMPERSAND) {
				{
				State = 183;
				Match(AMPERSAND);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NameContext : ParserRuleContext {
		public NameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name; } }
	 
		public NameContext() { }
		public virtual void CopyFrom(NameContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class StaticAccessNameContext : NameContext {
		public NameContext parent;
		public NameContext child;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_COLON() { return GetToken(HayParser.DOUBLE_COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NameContext[] name() {
			return GetRuleContexts<NameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NameContext name(int i) {
			return GetRuleContext<NameContext>(i);
		}
		public StaticAccessNameContext(NameContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStaticAccessName(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class MemberAccessNameContext : NameContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(HayParser.IDENTIFIER, 0); }
		public MemberAccessNameContext(NameContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMemberAccessName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NameContext name() {
		return name(0);
	}

	private NameContext name(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		NameContext _localctx = new NameContext(Context, _parentState);
		NameContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_name, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			_localctx = new MemberAccessNameContext(_localctx);
			Context = _localctx;
			_prevctx = _localctx;

			State = 187;
			Match(IDENTIFIER);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 194;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new StaticAccessNameContext(new NameContext(_parentctx, _parentState));
					((StaticAccessNameContext)_localctx).parent = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_name);
					State = 189;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 190;
					Match(DOUBLE_COLON);
					State = 191;
					((StaticAccessNameContext)_localctx).child = name(3);
					}
					} 
				}
				State = 196;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,17,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class NumberContext : ParserRuleContext {
		public NumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_number; } }
	 
		public NumberContext() { }
		public virtual void CopyFrom(NumberContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class HexIntegerContext : NumberContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HEX_INT() { return GetToken(HayParser.HEX_INT, 0); }
		public HexIntegerContext(NumberContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitHexInteger(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DecimalIntegerContext : NumberContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEC_INT() { return GetToken(HayParser.DEC_INT, 0); }
		public DecimalIntegerContext(NumberContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDecimalInteger(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class DoubleContext : NumberContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEC_DOUBLE() { return GetToken(HayParser.DEC_DOUBLE, 0); }
		public DoubleContext(NumberContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDouble(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberContext number() {
		NumberContext _localctx = new NumberContext(Context, State);
		EnterRule(_localctx, 36, RULE_number);
		try {
			State = 200;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case DEC_INT:
				_localctx = new DecimalIntegerContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 197;
				Match(DEC_INT);
				}
				break;
			case HEX_INT:
				_localctx = new HexIntegerContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 198;
				Match(HEX_INT);
				}
				break;
			case DEC_DOUBLE:
				_localctx = new DoubleContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 199;
				Match(DEC_DOUBLE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(HayParser.STRING, 0); }
		public StringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_string; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IHayVisitor<TResult> typedVisitor = visitor as IHayVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringContext @string() {
		StringContext _localctx = new StringContext(Context, State);
		EnterRule(_localctx, 38, RULE_string);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 202;
			Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 15: return expression_sempred((ExpressionContext)_localctx, predIndex);
		case 17: return name_sempred((NameContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 1);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		}
		return true;
	}
	private bool name_sempred(NameContext _localctx, int predIndex) {
		switch (predIndex) {
		case 3: return Precpred(Context, 2);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,26,205,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,1,0,5,0,42,8,0,10,0,
		12,0,45,9,0,1,0,1,0,5,0,49,8,0,10,0,12,0,52,9,0,1,0,1,0,1,1,1,1,1,1,1,
		1,1,2,1,2,1,2,1,2,1,3,1,3,3,3,66,8,3,1,4,1,4,1,4,1,4,1,5,1,5,5,5,74,8,
		5,10,5,12,5,77,9,5,1,5,5,5,80,8,5,10,5,12,5,83,9,5,1,5,1,5,1,6,1,6,1,6,
		1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,8,1,8,1,8,3,8,100,8,8,1,8,1,8,1,8,1,8,1,
		8,1,8,1,8,1,8,1,9,1,9,5,9,112,8,9,10,9,12,9,115,9,9,1,9,1,9,1,10,1,10,
		1,10,1,10,1,10,1,10,3,10,125,8,10,1,10,1,10,1,10,1,10,3,10,131,8,10,1,
		11,1,11,1,11,1,11,1,11,1,12,1,12,1,12,5,12,141,8,12,10,12,12,12,144,9,
		12,3,12,146,8,12,1,13,1,13,1,13,1,13,1,14,1,14,1,14,5,14,155,8,14,10,14,
		12,14,158,9,14,1,15,1,15,1,15,1,15,3,15,164,8,15,1,15,1,15,1,15,1,15,1,
		15,1,15,1,15,1,15,1,15,3,15,175,8,15,1,15,5,15,178,8,15,10,15,12,15,181,
		9,15,1,16,1,16,3,16,185,8,16,1,17,1,17,1,17,1,17,1,17,1,17,5,17,193,8,
		17,10,17,12,17,196,9,17,1,18,1,18,1,18,3,18,201,8,18,1,19,1,19,1,19,0,
		2,30,34,20,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,0,0,
		208,0,43,1,0,0,0,2,55,1,0,0,0,4,59,1,0,0,0,6,65,1,0,0,0,8,67,1,0,0,0,10,
		71,1,0,0,0,12,86,1,0,0,0,14,92,1,0,0,0,16,96,1,0,0,0,18,109,1,0,0,0,20,
		130,1,0,0,0,22,132,1,0,0,0,24,145,1,0,0,0,26,147,1,0,0,0,28,151,1,0,0,
		0,30,163,1,0,0,0,32,182,1,0,0,0,34,186,1,0,0,0,36,200,1,0,0,0,38,202,1,
		0,0,0,40,42,3,2,1,0,41,40,1,0,0,0,42,45,1,0,0,0,43,41,1,0,0,0,43,44,1,
		0,0,0,44,46,1,0,0,0,45,43,1,0,0,0,46,50,3,4,2,0,47,49,3,6,3,0,48,47,1,
		0,0,0,49,52,1,0,0,0,50,48,1,0,0,0,50,51,1,0,0,0,51,53,1,0,0,0,52,50,1,
		0,0,0,53,54,5,0,0,1,54,1,1,0,0,0,55,56,5,4,0,0,56,57,3,34,17,0,57,58,5,
		21,0,0,58,3,1,0,0,0,59,60,5,6,0,0,60,61,3,34,17,0,61,62,5,21,0,0,62,5,
		1,0,0,0,63,66,3,8,4,0,64,66,3,16,8,0,65,63,1,0,0,0,65,64,1,0,0,0,66,7,
		1,0,0,0,67,68,5,7,0,0,68,69,5,26,0,0,69,70,3,10,5,0,70,9,1,0,0,0,71,75,
		5,18,0,0,72,74,3,12,6,0,73,72,1,0,0,0,74,77,1,0,0,0,75,73,1,0,0,0,75,76,
		1,0,0,0,76,81,1,0,0,0,77,75,1,0,0,0,78,80,3,14,7,0,79,78,1,0,0,0,80,83,
		1,0,0,0,81,79,1,0,0,0,81,82,1,0,0,0,82,84,1,0,0,0,83,81,1,0,0,0,84,85,
		5,19,0,0,85,11,1,0,0,0,86,87,5,8,0,0,87,88,5,16,0,0,88,89,3,24,12,0,89,
		90,5,17,0,0,90,91,3,18,9,0,91,13,1,0,0,0,92,93,3,32,16,0,93,94,5,26,0,
		0,94,95,5,21,0,0,95,15,1,0,0,0,96,99,5,5,0,0,97,98,5,25,0,0,98,100,3,34,
		17,0,99,97,1,0,0,0,99,100,1,0,0,0,100,101,1,0,0,0,101,102,5,26,0,0,102,
		103,5,16,0,0,103,104,3,24,12,0,104,105,5,17,0,0,105,106,5,22,0,0,106,107,
		3,32,16,0,107,108,3,18,9,0,108,17,1,0,0,0,109,113,5,18,0,0,110,112,3,20,
		10,0,111,110,1,0,0,0,112,115,1,0,0,0,113,111,1,0,0,0,113,114,1,0,0,0,114,
		116,1,0,0,0,115,113,1,0,0,0,116,117,5,19,0,0,117,19,1,0,0,0,118,131,5,
		21,0,0,119,120,3,22,11,0,120,121,5,21,0,0,121,131,1,0,0,0,122,124,5,9,
		0,0,123,125,3,30,15,0,124,123,1,0,0,0,124,125,1,0,0,0,125,126,1,0,0,0,
		126,131,5,21,0,0,127,128,3,30,15,0,128,129,5,21,0,0,129,131,1,0,0,0,130,
		118,1,0,0,0,130,119,1,0,0,0,130,122,1,0,0,0,130,127,1,0,0,0,131,21,1,0,
		0,0,132,133,3,32,16,0,133,134,5,26,0,0,134,135,5,15,0,0,135,136,3,30,15,
		0,136,23,1,0,0,0,137,142,3,26,13,0,138,139,5,24,0,0,139,141,3,26,13,0,
		140,138,1,0,0,0,141,144,1,0,0,0,142,140,1,0,0,0,142,143,1,0,0,0,143,146,
		1,0,0,0,144,142,1,0,0,0,145,137,1,0,0,0,145,146,1,0,0,0,146,25,1,0,0,0,
		147,148,3,32,16,0,148,149,5,26,0,0,149,150,5,21,0,0,150,27,1,0,0,0,151,
		156,3,30,15,0,152,153,5,24,0,0,153,155,3,30,15,0,154,152,1,0,0,0,155,158,
		1,0,0,0,156,154,1,0,0,0,156,157,1,0,0,0,157,29,1,0,0,0,158,156,1,0,0,0,
		159,160,6,15,-1,0,160,164,3,36,18,0,161,164,3,38,19,0,162,164,3,34,17,
		0,163,159,1,0,0,0,163,161,1,0,0,0,163,162,1,0,0,0,164,179,1,0,0,0,165,
		166,10,1,0,0,166,167,5,15,0,0,167,178,3,30,15,2,168,169,10,3,0,0,169,170,
		5,23,0,0,170,178,5,26,0,0,171,172,10,2,0,0,172,174,5,16,0,0,173,175,3,
		28,14,0,174,173,1,0,0,0,174,175,1,0,0,0,175,176,1,0,0,0,176,178,5,17,0,
		0,177,165,1,0,0,0,177,168,1,0,0,0,177,171,1,0,0,0,178,181,1,0,0,0,179,
		177,1,0,0,0,179,180,1,0,0,0,180,31,1,0,0,0,181,179,1,0,0,0,182,184,3,34,
		17,0,183,185,5,14,0,0,184,183,1,0,0,0,184,185,1,0,0,0,185,33,1,0,0,0,186,
		187,6,17,-1,0,187,188,5,26,0,0,188,194,1,0,0,0,189,190,10,2,0,0,190,191,
		5,20,0,0,191,193,3,34,17,3,192,189,1,0,0,0,193,196,1,0,0,0,194,192,1,0,
		0,0,194,195,1,0,0,0,195,35,1,0,0,0,196,194,1,0,0,0,197,201,5,11,0,0,198,
		201,5,12,0,0,199,201,5,13,0,0,200,197,1,0,0,0,200,198,1,0,0,0,200,199,
		1,0,0,0,201,37,1,0,0,0,202,203,5,10,0,0,203,39,1,0,0,0,19,43,50,65,75,
		81,99,113,124,130,142,145,156,163,174,177,179,184,194,200
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
