//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/dimitarbogdanov/Documents/Projects/hayc/HaycLib/Hay.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


// CLI compliance attribute
#pragma warning disable CS3021
namespace HaycLib.Antlr;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HayParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IHayVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] HayParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.namespaceImport"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceImport([NotNull] HayParser.NamespaceImportContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceDeclaration([NotNull] HayParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.topLevelConstruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTopLevelConstruct([NotNull] HayParser.TopLevelConstructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaration([NotNull] HayParser.StructDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructBody([NotNull] HayParser.StructBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.structInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructInitializer([NotNull] HayParser.StructInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.structField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructField([NotNull] HayParser.StructFieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.functionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDeclaration([NotNull] HayParser.FunctionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.statementBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementBlock([NotNull] HayParser.StatementBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyStatement</c>
	/// labeled alternative in <see cref="HayParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyStatement([NotNull] HayParser.EmptyStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariableDeclarationStatement</c>
	/// labeled alternative in <see cref="HayParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclarationStatement([NotNull] HayParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnStatement</c>
	/// labeled alternative in <see cref="HayParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] HayParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpressionStatement</c>
	/// labeled alternative in <see cref="HayParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] HayParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] HayParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] HayParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] HayParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] HayParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NameReferenceExpression</c>
	/// labeled alternative in <see cref="HayParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNameReferenceExpression([NotNull] HayParser.NameReferenceExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringExpression</c>
	/// labeled alternative in <see cref="HayParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpression([NotNull] HayParser.StringExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumberExpression</c>
	/// labeled alternative in <see cref="HayParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberExpression([NotNull] HayParser.NumberExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AccessExpression</c>
	/// labeled alternative in <see cref="HayParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessExpression([NotNull] HayParser.AccessExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VariableAssignmentExpression</c>
	/// labeled alternative in <see cref="HayParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignmentExpression([NotNull] HayParser.VariableAssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionCallExpression</c>
	/// labeled alternative in <see cref="HayParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionCallExpression([NotNull] HayParser.FunctionCallExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] HayParser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StaticAccessName</c>
	/// labeled alternative in <see cref="HayParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticAccessName([NotNull] HayParser.StaticAccessNameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MemberAccessName</c>
	/// labeled alternative in <see cref="HayParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccessName([NotNull] HayParser.MemberAccessNameContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>DecimalInteger</c>
	/// labeled alternative in <see cref="HayParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalInteger([NotNull] HayParser.DecimalIntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>HexInteger</c>
	/// labeled alternative in <see cref="HayParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHexInteger([NotNull] HayParser.HexIntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>Double</c>
	/// labeled alternative in <see cref="HayParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDouble([NotNull] HayParser.DoubleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HayParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] HayParser.StringContext context);
}
