//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/SoftwareProjects/Hayc/Hayc\Hay.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Hayc.Antlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HayParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IHayListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HayParser.chat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChat([NotNull] HayParser.ChatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HayParser.chat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChat([NotNull] HayParser.ChatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HayParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] HayParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HayParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] HayParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HayParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterName([NotNull] HayParser.NameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HayParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitName([NotNull] HayParser.NameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HayParser.opinion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpinion([NotNull] HayParser.OpinionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HayParser.opinion"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpinion([NotNull] HayParser.OpinionContext context);
}
} // namespace Hayc.Antlr
